# 注意：watchalert-service 暂不支持多副本
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: watchalert-service
  name: watchalert-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watchalert-service
  template:
    metadata:
      labels:
        app: watchalert-service

    spec:
      containers:
        - name: watchalert-service
          image: docker.io/cairry/watchalert:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9001
              name: http
              protocol: TCP

          resources:
            limits:
              cpu: "1"
              memory: 2G
            requests:
              cpu: 100m
              memory: 100M

          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /hello
              port: 9001
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 1
            httpGet:
              path: /hello
              port: 9001
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1

          volumeMounts:
            - mountPath: /app/config/config.yaml
              name: config
              subPath: config.yaml
            - mountPath: /etc/localtime
              name: host-time

      volumes:
        - configMap:
            defaultMode: 420
            name: watchalert
          name: config
        - hostPath:
            path: /etc/localtime
            type: ""
          name: host-time

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: watchalert-web
  name: watchalert-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watchalert-web
  template:
    metadata:
      labels:
        app: watchalert-web

    spec:
      containers:
        - name: watchalert-web
          image: docker.io/cairry/watchalert-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
              protocol: TCP

          resources:
            limits:
              cpu: "1"
              memory: 2G
            requests:
              cpu: 100m
              memory: 100M

          volumeMounts:
            - mountPath: /etc/nginx/conf.d/w8t.conf
              name: nginx-config
              subPath: w8t.conf
            - mountPath: /etc/localtime
              name: host-time

      volumes:
        - configMap:
            defaultMode: 420
            name: watchalert
          name: nginx-config
        - hostPath:
            path: /etc/localtime
            type: ""
          name: host-time
